import { StyleSheet } from "react-native-unistyles";

export const common = {
  fonts: {
    thin: "System",
    extralight: "System",
    light: "System",
    regular: "System",
    medium: "System",
    semibold: "System",
    bold: "System",
    extrabold: "System",
    black: "System",
  },
  shadow: {
    xs: {
      shadowColor: "rgba(0,0,0,0.05)",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 1,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "rgba(0,0,0,0.08)",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 6,
      elevation: 4,
    },
    xl: {
      shadowColor: "rgba(0,0,0,0.1)",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 8,
    },
    "2xl": {
      shadowColor: "rgba(0,0,0,0.12)",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 1,
      shadowRadius: 16,
      elevation: 12,
    },
    "3xl": {
      shadowColor: "rgba(0,0,0,0.15)",
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 1,
      shadowRadius: 24,
      elevation: 16,
    },
  },
  sizes: {
    fonts: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 20,
      "2xl": 24,
      "3xl": 30,
      "4xl": 36,
      "5xl": 48,
      "6xl": 64,
      "7xl": 72,
      "8xl": 96,
      "9xl": 128,
    },
    spacing: (n: number) => n * 4,
    h: (n: number) => n * 4,
    w: (n: number) => n * 4,
    gap: (n: number) => n * 4,
    p: (n: number) => n * 4,
    m: (n: number) => n * 4,
  },
};

export const light = {
  ...common,
  colors: {
    background: "#ffffff",
    foreground: "#000000",
    card: "#ffffff",
    cardForeground: "#000000",
    popover: "#ffffff",
    popoverForeground: "#000000",
    primary: "#020202",
    primaryForeground: "#f3f3f3",
    secondary: "#F5F5F5",
    secondaryForeground: "#020202",
    muted: "#e8e8e8",
    mutedForeground: "#737373",
    accent: "#e8e8e8",
    accentForeground: "#020202",
    destructive: "#cc0000",
    destructiveForeground: "#ffffff",
    border: "#c7c7c7",
    input: "transparent",
    inputSurface: "#E5E5E5",
    ring: "#5a5a5a",
    chart1: "#e81100",
    chart2: "#004e3f",
    chart3: "#011320",
    chart4: "#ff7c00",
    chart5: "#fb5100",
    sidebar: "#f3f3f3",
    sidebarForeground: "#000000",
    sidebarPrimary: "#020202",
    sidebarPrimaryForeground: "#f3f3f3",
    sidebarAccent: "#e8e8e8",
    sidebarAccentForeground: "#020202",
    sidebarBorder: "#c7c7c7",
    sidebarRing: "#5a5a5a",
  },
  radii: {
    base: 10,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
    full: 9999,
  },
};

export const dark = {
  ...common,
  colors: {
    background: "#727272",
    foreground: "#fdfdfd",
    card: "#171717",
    cardForeground: "#fdfdfd",
    popover: "#848484",
    popoverForeground: "#fdfdfd",
    primary: "#f7f7f7",
    primaryForeground: "#848484",
    secondary: "#949494",
    secondaryForeground: "#fdfdfd",
    muted: "#949494",
    destructiveForeground: "#ffffff",
    mutedForeground: "#A1A1A1",
    accent: "#949494",
    accentForeground: "#fdfdfd",
    destructive: "#d8403d",
    border: "#2E2E2E",
    input: "#212121",
    inputSurface: "#212121",
    ring: "#c8c8c8",
    chart1: "#4339f2",
    chart2: "#3dd68c",
    chart3: "#f6c244",
    chart4: "#8c3ffc",
    chart5: "#f95738",
    sidebar: "#848484",
    sidebarForeground: "#fdfdfd",
    sidebarPrimary: "#4339f2",
    sidebarPrimaryForeground: "#fdfdfd",
    sidebarAccent: "#949494",
    sidebarAccentForeground: "#fdfdfd",
    sidebarBorder: "#ffffff",
    sidebarRing: "#c8c8c8",
  },
  radii: {
    base: 10,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
    full: 9999,
  },
};
export const themes = { light, dark } as const;
export const breakpoints = {
  xs: 0,
  sm: 360,
  md: 768,
  lg: 1024,
  xl: 1280,
} as const;

type AppThemes = typeof themes;
type AppBreakpoints = typeof breakpoints;
declare module "react-native-unistyles" {
  export interface UnistylesThemes extends AppThemes {}
  export interface UnistylesBreakpoints extends AppBreakpoints {}
}

StyleSheet.configure({
  themes,
  breakpoints,
  settings: { initialTheme: "light" }, // auto light/dark2
});
